import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
export const apiSlice = createApi({
  reducerPath: "api",
  baseQuery: fetchBaseQuery({
    baseUrl: `${import.meta.env.VITE_API_ROOT}api/`,
  }),
  tagTypes: [
    "HOTEL",
    "Category",
    "Restaurant",
    "Item",
    "Menu",
    "Location",
    "Items",
    "itemId",
    "Payment",
    "Account",
    "Orders",
    "SpendXSaveY",
    "Voucher",
    "Bogo",
    "GroupOrdering",
    "LoyaltyProgram",
    "birthdayGift",
    "giftCard",
    "membershipCard",
    "GroupInvitation",
    "FissionCampaign",
    "WhatsApp",
    "SMS",
    "Rewards",
    "ModifierGroup",
    "RewardsGroup",
    "Themes",
    "DELIVERY_FEES",
    "Invoice",
    "AutoReplyReview",
  ],
  endpoints: (builder) => ({}),
});
